package View;

import Controller.PetsXML_Controller;

import javax.swing.*;
import java.awt.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Base64;

public class Customer_Pet_Profile_View extends javax.swing.JFrame {

    private static String username;
    private static String serverAddress;
    private static int serverPort;
    private static String id;
    private static String breed;
    private static String type;
    private static String age;
    private static String healthStatus;
    private static String adoptionStatus;
    private static Object image;

    /**
     * Creates new form Customer_Pet_Profile_View
     */
    public Customer_Pet_Profile_View(String username, String id, String breed, String type, String age,
                                     String healthStatus, String adoptionStatus, Object image, String serverAddress, int serverPort) {
        this.username = username;
        this.serverAddress = serverAddress;
        this.serverPort = serverPort;
        this.id = id;
        this.breed = breed;
        this.type = type;
        this.age = age;
        this.healthStatus = healthStatus;
        this.adoptionStatus = adoptionStatus;
        this.image = image;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        picture_Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        id_Label = new javax.swing.JLabel();
        breed_Label = new javax.swing.JLabel();
        type_Label = new javax.swing.JLabel();
        age_Label = new javax.swing.JLabel();
        healthyStatus_Label = new javax.swing.JLabel();
        adoptionStatus_Label = new javax.swing.JLabel();
        displayID_Label = new javax.swing.JLabel();
        displayBreed_Label = new javax.swing.JLabel();
        displayType_Label = new javax.swing.JLabel();
        displayAge_Label = new javax.swing.JLabel();
        displayHealthyStatus_Label = new javax.swing.JLabel();
        displayAdoptionStatus_Label = new javax.swing.JLabel();
        adoptButton = new javax.swing.JButton();
        back_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        picture_Label.setBackground(new java.awt.Color(204, 204, 204));
        picture_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        try (Socket socket = new Socket(serverAddress, serverPort);
             PrintWriter writer = new PrintWriter(socket.getOutputStream(), true);
             BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()))) {

            writer.println("pet-icon");
            Thread.sleep(50);
            writer.println(id);
            Thread.sleep(50);

            String base64Image = reader.readLine();

            if (base64Image != null && !"not-found".equalsIgnoreCase(base64Image)) {
                // Step 4: Decode the Base64 image string
                byte[] imageBytes = Base64.getDecoder().decode(base64Image);
                ImageIcon icon = new ImageIcon(imageBytes);

                Image scaledImage = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(scaledImage);

                picture_Label.setIcon(scaledIcon);
            } else {
                picture_Label.setIcon(null);
            }

        } catch (IOException | InterruptedException ex) {
            ex.printStackTrace();
        }
        picture_Label.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 255), new java.awt.Color(204, 255, 255)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(51, 153, 255), new java.awt.Color(102, 153, 255)));

        id_Label.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        id_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        id_Label.setText("ID :");

        breed_Label.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        breed_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        breed_Label.setText("BREED :");

        type_Label.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        type_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        type_Label.setText("TYPE :");

        age_Label.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        age_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        age_Label.setText("AGE :");

        healthyStatus_Label.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        healthyStatus_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        healthyStatus_Label.setText("HEALTH STATUS :");

        adoptionStatus_Label.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        adoptionStatus_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adoptionStatus_Label.setText("ADOPTION STATUS :");

        // Set the display labels using the correct variables
        displayID_Label.setText(id);
        displayBreed_Label.setText(breed);
        displayType_Label.setText(type);
        displayAge_Label.setText(age);
        displayHealthyStatus_Label.setText(healthStatus);
        displayAdoptionStatus_Label.setText(adoptionStatus);
        if (adoptionStatus != null && adoptionStatus.equalsIgnoreCase("Adopted")) {
            adoptButton.setVisible(false);
        } else {
            adoptButton.setVisible(true);
        }


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(age_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(type_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(breed_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(displayBreed_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(displayID_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(displayAge_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(displayType_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(healthyStatus_Label)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(displayHealthyStatus_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(adoptionStatus_Label)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(displayAdoptionStatus_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(displayID_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(breed_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(displayBreed_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(type_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(displayType_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(age_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(displayAge_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(healthyStatus_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(displayHealthyStatus_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(adoptionStatus_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(displayAdoptionStatus_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(138, 138, 138))
        );

       adoptButton.setText("Apply For Adoption");
        adoptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply_AdoptionActionPerformed(evt);
            }
        });

        back_Button.setText("< Back");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(adoptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(49, 49, 49))
                                        .addComponent(picture_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(back_Button)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(back_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(picture_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(145, 145, 145)
                                                .addComponent(adoptButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );

        pack();
    }// </editor-fold>

    private void apply_AdoptionActionPerformed(java.awt.event.ActionEvent evt) {
        // If serverAddress is null, default it to "localhost"
        String serverAddr = (serverAddress == null) ? "localhost" : serverAddress;
        SwingUtilities.invokeLater(() -> {
            Customer_AdoptionForm_View customerAdoptionFormView = new Customer_AdoptionForm_View(
                    username, id, breed, type, age, healthStatus, adoptionStatus, image, serverAddress, serverPort
            );
            customerAdoptionFormView.setVisible(true);
        });
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Pet_Profile_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Pet_Profile_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Pet_Profile_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Pet_Profile_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Pet_Profile_View(username, id, breed, type, age, healthStatus, adoptionStatus, image, serverAddress,serverPort).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel adoptionStatus_Label;
    private javax.swing.JLabel age_Label;
    private javax.swing.JButton back_Button;
    private javax.swing.JLabel breed_Label;
    private javax.swing.JLabel displayAdoptionStatus_Label;
    private javax.swing.JLabel displayAge_Label;
    private javax.swing.JLabel displayBreed_Label;
    private javax.swing.JLabel displayHealthyStatus_Label;
    private javax.swing.JLabel displayID_Label;
    private javax.swing.JLabel displayType_Label;
    private javax.swing.JLabel healthyStatus_Label;
    private javax.swing.JLabel id_Label;
    private javax.swing.JButton adoptButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel picture_Label;
    private javax.swing.JLabel type_Label;
    // End of variables declaration
}
